### ISSUE TITLE
Pb avec les photo

### ISSUE THREAD

**Issue by UnderSkyle** [QuentinANIERE/PierreFeuilleCiseaux#1]
couldn't open "medias/pierre.png": no such file or directory

**Comment by qaniere** [comment]
Question bête, tu a bien téléchargé tout les fichiers ? 

Sinon, tu l'execute avec quoi, parce VsCode/Powershell peut causer ce genre de soucis

**Comment by UnderSkyle** [comment]
J ai biens tt dl et je lance avec visual studio code.

**Comment by qaniere** [comment]
Visual Studio Code à quelques difficultés à lire les médias :(

 - Soit tu l'ouvre avec tu ouvre simplement le fichier, ce qui marche très bien sur mes trois ordis
- Sois tu rajoute import os et os.chdir(r"CheminDossierScript") au début du code

**Comment by UnderSkyle** [comment]
Ok je vais esseyer

**Comment by UnderSkyle** [comment]
ça marche mtn j ai juste lancer avec l'idle

**Comment by qaniere** [comment]
Nice :)
